config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # get "tasks", to: "tasks#index" 
  # get "tasks/new", to:"tasks#new", as: :new_task
  # get "tasks/:id", to:"tasks#show", as: :task
  # get "tasks/:id/edit", to: "tasks#edit", as: :edit_task
  # delete "tasks/:id", to: "tasks#destroy"
  # patch "tasks/:id", to: "tasks#update"
  # post "tasks", to:"tasks#create"
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :set_task, only: [:show, :edit, :update, :destroy]
    def index
        @tasks = Task.all
    end

    def show
    end

    def new
        @task = Task.new
    end

    def create
        @task = Task.create(task_params)
        redirect_to task_path(@task)
    end

    def edit
    end

    def update
        @task.update(task_params)
        redirect_to task_path(@task)
    end

    def destroy
        @task.destroy
        redirect_to tasks_path
    end

    private

    def set_task
        @task = Task.find(params[:id])
    end

    def task_params
        params.require(:task).permit(:title, :details, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Upgrade a Task</h1>
<%= render "form", task: @task %>

app/views/tasks/index.html.erb
<div class="container">
    <h1>Tasks</h1>
    <ul>
    <% @tasks.each do |task|  %>
        <li><%=task.completed%><%= link_to task.title, task_path(task)%> <%= link_to "🗑️", task_path(task), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></li>
    <%end  %>
    </ul>
    <button class ="btn btn-info"><%= link_to "Create", new_task_path  %></button>
</div>

app/views/tasks/new.html.erb
<h1>New Task</h1>
<%= render "form", task: @task %>

app/views/tasks/show.html.erb
<h2><%= @task.title %></h2>
<p><%= @task.details %></p>
<p><%= @task.completed ? "✅ Completed" : "❌ Not completed"%></p>

<%= link_to "Back to list", tasks_path %><br>
<%= link_to "Edit this task", edit_task_path(@task) %>